[package]
name = "move"
version = "0.8.6"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
csv = "1.3.1"
dirs = "6.0.0"
dotenv = "0.15.0"
rusqlite = "0.33.0"
tabled = "0.17.0"
