[package]
name = "move"
version = "0.6.6"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
csv = "1.3.1"
dirs = "6.0.0"
dotenv = "0.15.0"
postgres = "0.19.9"
tabled = "0.17.0"
